runtime: java11
entrypoint: 'java -cp "*" com.google.musicanalysis.jettymain.Main site.war'

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /static
    static_dir: ../client

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
